

-- Tables principales :
TRUNCATE TABLE historique_etapes RESTART IDENTITY CASCADE;
TRUNCATE TABLE etape_travaux RESTART IDENTITY CASCADE;
TRUNCATE TABLE point_de_reparation RESTART IDENTITY CASCADE;
TRUNCATE TABLE entreprise RESTART IDENTITY CASCADE;
TRUNCATE TABLE login_attempts RESTART IDENTITY CASCADE;
TRUNCATE TABLE utilisateur RESTART IDENTITY CASCADE;
TRUNCATE TABLE role RESTART IDENTITY CASCADE;
TRUNCATE TABLE configuration RESTART IDENTITY CASCADE;

-- Si tu as une table pour les FCM tokens :
TRUNCATE TABLE user_fcm_tokens RESTART IDENTITY CASCADE;
